name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run OCI Emulator
        run: docker run -d --name oci-emulator -p 12000:12000 cameritelabs/oci-emulator:latest

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: install tarpaulin
        run: cargo install cargo-tarpaulin
        
      - name: run tarpaulin
        run: cargo tarpaulin --out Lcov

      - name: Codecov
        uses: codecov/codecov-action@v5.3.1
        with:
          verbose: true
          fail_ci_if_error: true

  build_publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
          ignore-unpublished-changes: true
